server:  port: 8085  

   
spring:
  cloud:
    gateway:
      routes:
      - id: Product-Server           
        uri: http://localhost:8082/                 #Respective microservice URL which needs to be mapped
         #Request Context Path Mapping
        predicates:
        - Path=/api/product/**                 - id: cart-service                  uri: http://localhost:8084/                 #Respective microservice URL which needs to be mapped         #Request Context Path Mapping        predicates:        - Path=/api/cart/**         
           - id: order-service                  uri: http://localhost:8083/                 #Respective microservice URL which needs to be mapped         #Request Context Path Mapping        predicates:        - Path=/api/order/**                     - id: Profile-service                  uri: http://localhost:8081/                 #Respective microservice URL which needs to be mapped         #Request Context Path Mapping        predicates:        - Path=/api/auth/**      application:    name: Api-Gateway